### ISSUE TITLE
Send requirement for AsyncProgressView

### ISSUE THREAD

**Issue by mrd0ll4r** [deinstapel/cursive-async-view#3]
Hey!
I'm somewhat new to Rust, and I'm writing a terminal application that, among other things, loads some stuff from a database and displays it as a table. I'm using the [cursive_table_view](https://crates.io/crates/cursive_table_view) crate for the table, and that works, but I was staring at a static screen whenever I was loading new data, so I though: Why not use this cool crate to show a loading bar?

And so I did, and it works!
Now, the thing is: I load a bunch of rows in an initial query, and then I need to load additional info for each record. Which means I need to do many queries, but I know how many, so I want to display a progress bar that tells the user how far along we are.
So I simply replaced all the `AsyncView`s with `AsyncProgressView`s, and `AsyncState`s with `AsyncProgressState`s, and compilation fails.

The problem is that the table view is not `Send`, so (I think) the `AsyncProgressView<TableView>` is not a `View`.
I could be missing something, again -- not a veteran.
Any ideas?

**Comment by fin-ger** [comment]
I think this is a bug on our side. We previously had a `Send` requirement on our views, but as most cursive views are not `Send` we removed this restriction and introduced a new API making use of the send_wrapper crate. Technically we are scheduling the "waiting" for the async view in the cursive thread, which makes sure a View never has to be sent between threads. We are currently fixing this issue and testing if everything is still working.

**Comment by fia0** [comment]
Hey @mrd0ll4r, first of all thanks for using this crate :smile:
I pushed a fix and tested it with some non-sendable views from cursive, everything seems to work, it was simply a requirement we no longer needed. Atm releasing a patch release, your issue should be resolved with release `0.3.4`. If you still encountered any troubles please let us know.

**Comment by fia0** [comment]
Fixed by 4060fe651d75a35ef9a41ed62d9921946795c5de.

**Comment by mrd0ll4r** [comment]
Oh no, I lost track of this and didn't get around to test it, so sorry!
I tried it now and it works beautifully, thank you! :)

**Comment by fia0** [comment]
No worries, it's good to hear that it now works for you :D
