### ISSUE TITLE
Adding method to modify the default `loading` in `AsyncView`

### ISSUE THREAD

**Issue by aome510** [deinstapel/cursive-async-view#9]
Is it possible to add a method like `set_loading` to modify the `loading` field in a `AsyncView` struct?

I want to center the loading animation but find it impossible because I cannot change the default `loading` field, which is a `TextView` without the `center` alignment option.

**Comment by fin-ger** [comment]
I am not sure whether I understand the problem correctly, but I assume you want to center the displayed content of the progressbar, e.g. the animation, the error messages, the success message, etc.?

We have another crate which handles the alignment of any view: [`cursive-aligned-view`](https://github.com/deinstapel/cursive-aligned-view).

I assembled a quick example with [`cargo play`](https://crates.io/crates/cargo-play) on how to center a progress bar using the `Alignable` trait:

<details>
<summary>Code</summary>

```rust
//# cursive = "*"
//# cursive-async-view = "*"
//# cursive-aligned-view = "*"

use cursive::{
    self, view::Resizable, views::Dialog, views::LinearLayout, views::TextView, Cursive, CursiveExt,
};
use cursive_aligned_view::Alignable;
use cursive_async_view::{AsyncProgressState, AsyncProgressView};
use std::time::{Duration, Instant};

fn main() {
    cursive::logger::init();

    let mut siv = Cursive::default();

    // We can quit by pressing `q`
    siv.add_global_callback('q', Cursive::quit);

    let start = Instant::now();

    let async_view = AsyncProgressView::new(&mut siv, move || {
        if start.elapsed() > Duration::from_secs(5) {
            AsyncProgressState::Available(TextView::new("🦀 Yay, the content has loaded! 🦀"))
        } else {
            AsyncProgressState::Pending(1f32 / 5f32 * start.elapsed().as_secs() as f32)
        }
    })
    .with_width(40);

    let content = LinearLayout::vertical()
        .child(TextView::new(
            "This is a very long title to make it wider than the progress bar",
        ))
        .child(async_view.align_center().fixed_height(1));

    let dialog = Dialog::around(content).button("Ok", |s| s.quit());

    siv.add_layer(dialog);
    siv.run();
}
```

Save this to a file (e.g. `centered_async_view.rs`) and run it with `cargo play centered_async_view.rs`.

</details>

Does this solve your problem?

**Comment by aome510** [comment]
> I am not sure whether I understand the problem correctly, but I assume you want to center the displayed content of the progressbar, e.g. the animation, the error messages, the success message, etc.?

Yeah, that is what I want. 

> We have another crate which handles the alignment of any view: cursive-aligned-view.

Just a while ago, I found `cursive-aligned-view` while finding a word-around for this issue. Didn't know that you are the maintainer for both. Thank you for creating such amazing packages!

> Does this solve your problem?

Yes, it solves my problem.
